package com.apps.miaowu.bean;

import java.util.Date;

public class Animal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.name
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.category
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.age
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.gender
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column animal.birthday
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Date birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.id
     *
     * @return the value of animal.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.id
     *
     * @param id the value for animal.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.name
     *
     * @return the value of animal.name
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.name
     *
     * @param name the value for animal.name
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.category
     *
     * @return the value of animal.category
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.category
     *
     * @param category the value for animal.category
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.age
     *
     * @return the value of animal.age
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.age
     *
     * @param age the value for animal.age
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.gender
     *
     * @return the value of animal.gender
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.gender
     *
     * @param gender the value for animal.gender
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column animal.birthday
     *
     * @return the value of animal.birthday
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column animal.birthday
     *
     * @param birthday the value for animal.birthday
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
}