package com.apps.miaowu.bean;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.write_date
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Date writeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.last_update
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.thump_up
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long thumpUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.animal_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long animalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.write_date
     *
     * @return the value of article.write_date
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Date getWriteDate() {
        return writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.write_date
     *
     * @param writeDate the value for article.write_date
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.last_update
     *
     * @return the value of article.last_update
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.last_update
     *
     * @param lastUpdate the value for article.last_update
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.thump_up
     *
     * @return the value of article.thump_up
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getThumpUp() {
        return thumpUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.thump_up
     *
     * @param thumpUp the value for article.thump_up
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setThumpUp(Long thumpUp) {
        this.thumpUp = thumpUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.animal_id
     *
     * @return the value of article.animal_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getAnimalId() {
        return animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.animal_id
     *
     * @param animalId the value for article.animal_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setAnimalId(Long animalId) {
        this.animalId = animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type
     *
     * @return the value of article.type
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type
     *
     * @param type the value for article.type
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}