package com.apps.miaowu.bean;

public class ArticleLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.bel
     *
     * @mbg.generated
     */
    private Long bel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.label_id
     *
     * @mbg.generated
     */
    private Long labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.article_id
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.bel
     *
     * @return the value of article_label.bel
     *
     * @mbg.generated
     */
    public Long getBel() {
        return bel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.bel
     *
     * @param bel the value for article_label.bel
     *
     * @mbg.generated
     */
    public void setBel(Long bel) {
        this.bel = bel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.label_id
     *
     * @return the value of article_label.label_id
     *
     * @mbg.generated
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.label_id
     *
     * @param labelId the value for article_label.label_id
     *
     * @mbg.generated
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.article_id
     *
     * @return the value of article_label.article_id
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.article_id
     *
     * @param articleId the value for article_label.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }
}