package com.apps.miaowu.bean;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.content
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.article_id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_table.user_id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.id
     *
     * @return the value of comment_table.id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.id
     *
     * @param id the value for comment_table.id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.content
     *
     * @return the value of comment_table.content
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.content
     *
     * @param content the value for comment_table.content
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.article_id
     *
     * @return the value of comment_table.article_id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.article_id
     *
     * @param articleId the value for comment_table.article_id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_table.user_id
     *
     * @return the value of comment_table.user_id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_table.user_id
     *
     * @param userId the value for comment_table.user_id
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}