package com.apps.miaowu.bean;

public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.name
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country._language
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private String language;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.name
     *
     * @return the value of country.name
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.name
     *
     * @param name the value for country.name
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country._language
     *
     * @return the value of country._language
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country._language
     *
     * @param language the value for country._language
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }
}