package com.apps.miaowu.bean;

import java.util.Date;

public class Found {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_table.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_table.user_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_table.animal_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Long animalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_table.site
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private String site;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column found_table.found_date
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    private Date foundDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_table.id
     *
     * @return the value of found_table.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_table.id
     *
     * @param id the value for found_table.id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_table.user_id
     *
     * @return the value of found_table.user_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_table.user_id
     *
     * @param userId the value for found_table.user_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_table.animal_id
     *
     * @return the value of found_table.animal_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Long getAnimalId() {
        return animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_table.animal_id
     *
     * @param animalId the value for found_table.animal_id
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setAnimalId(Long animalId) {
        this.animalId = animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_table.site
     *
     * @return the value of found_table.site
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_table.site
     *
     * @param site the value for found_table.site
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_table.found_date
     *
     * @return the value of found_table.found_date
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public Date getFoundDate() {
        return foundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_table.found_date
     *
     * @param foundDate the value for found_table.found_date
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    public void setFoundDate(Date foundDate) {
        this.foundDate = foundDate;
    }
}