package com.apps.miaowu.bean;

public class ArticleLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.label_id
     *
     * @mbg.generated
     */
    private Long labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_label.article_id
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.id
     *
     * @return the value of article_label.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.id
     *
     * @param id the value for article_label.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.label_id
     *
     * @return the value of article_label.label_id
     *
     * @mbg.generated
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.label_id
     *
     * @param labelId the value for article_label.label_id
     *
     * @mbg.generated
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_label.article_id
     *
     * @return the value of article_label.article_id
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_label.article_id
     *
     * @param articleId the value for article_label.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }
}