package com.apps.miaowu.bean;

import java.io.Serializable;
import java.util.Date;

public class Save implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.animal_id
     *
     * @mbg.generated
     */
    private Long animalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.save_date
     *
     * @mbg.generated
     */
    private Date saveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table save
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column save.id
     *
     * @return the value of save.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column save.id
     *
     * @param id the value for save.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column save.user_id
     *
     * @return the value of save.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column save.user_id
     *
     * @param userId the value for save.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column save.animal_id
     *
     * @return the value of save.animal_id
     *
     * @mbg.generated
     */
    public Long getAnimalId() {
        return animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column save.animal_id
     *
     * @param animalId the value for save.animal_id
     *
     * @mbg.generated
     */
    public void setAnimalId(Long animalId) {
        this.animalId = animalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column save.save_date
     *
     * @return the value of save.save_date
     *
     * @mbg.generated
     */
    public Date getSaveDate() {
        return saveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column save.save_date
     *
     * @param saveDate the value for save.save_date
     *
     * @mbg.generated
     */
    public void setSaveDate(Date saveDate) {
        this.saveDate = saveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", animalId=").append(animalId);
        sb.append(", saveDate=").append(saveDate);
        sb.append("]");
        return sb.toString();
    }
}