package com.apps.miaowu.dao;

import com.apps.miaowu.bean.Found;
import com.apps.miaowu.bean.FoundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    long countByExample(FoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int deleteByExample(FoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int insert(Found record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int insertSelective(Found record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    List<Found> selectByExample(FoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    Found selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Found record, @Param("example") FoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Found record, @Param("example") FoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Found record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table found_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Found record);
}