package com.apps.miaowu.dao;

import com.apps.miaowu.bean.Save;
import com.apps.miaowu.bean.SaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    long countByExample(SaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int deleteByExample(SaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int insert(Save record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int insertSelective(Save record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    List<Save> selectByExample(SaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    Save selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Save record, @Param("example") SaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int updateByExample(@Param("record") Save record, @Param("example") SaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int updateByPrimaryKeySelective(Save record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Mon Mar 30 23:04:18 CST 2020
     */
    int updateByPrimaryKey(Save record);
}