package com.apps.miaowu.dao;

import com.apps.miaowu.bean.ThumbUp;
import com.apps.miaowu.bean.ThumbUpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThumbUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    long countByExample(ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int deleteByExample(ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int insert(ThumbUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int insertSelective(ThumbUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    List<ThumbUp> selectByExample(ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    ThumbUp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") ThumbUp record, @Param("example") ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int updateByExample(@Param("record") ThumbUp record, @Param("example") ThumbUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int updateByPrimaryKeySelective(ThumbUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thumb_up
     *
     * @mbg.generated Sun Feb 23 20:26:21 CST 2020
     */
    int updateByPrimaryKey(ThumbUp record);
}